### ISSUE TITLE
Visual Studio Function Template host.json has samplingExcludedTypes

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-functions-templates#1001]
When i start a new project of azure functions the host.json looks like this:
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
              "isEnabled": true
               
            }
        }
    }
}
```

but samplingExcludedTypes is wrong per https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsights it should look like
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
              "isEnabled": true,
              "excludedTypes": "Request",
            }
        }
    }
}
```

found this because i noticed that by default my Request were getting throttled/sampled even though they were excluded (supposedly).

this issue probably needs to be routed soemwhere else, but i'm not really sure where it would go

**Comment by fabiocav** [comment]
Assigning to sprint 93 for completion.
