### ISSUE TITLE
C#(csx) template for EventHub extension needs to be changed

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-templates#1038]
v3 ExtensionBundle uses new version of EventHub  Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta.1:
https://github.com/Azure/azure-functions-extension-bundles/blob/v3.x/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L42

Current template is for Microsoft.Azure.WebJobs.Extensions.EventHubs 4.x. 

Repro project:
[test.zip](https://github.com/Azure/azure-functions-templates/files/6175015/test.zip)

![image](https://user-images.githubusercontent.com/2578359/111861653-44654600-890d-11eb-8145-241f00ef7411.png)

**Comment by fabiocav** [comment]
Link to the template that needs to be updated:

https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/EventHubTrigger-CSharp/EventHubTriggerCSharp.csx
https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/EventHubTrigger-CSharp/EventHubTriggerCSharp.cs

**Comment by soninaren** [comment]
Fixed in this commit 
https://github.com/Azure/azure-functions-templates/commit/44e0f3b1fa8755922044389f02a5e86f2645ddfe
