### ISSUE TITLE
Cannot build templates

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-functions-templates#1054]
I'm trying to build the templates on macOS Big Sur, on an Apple M1 MBA. When I run `nom build app`, I get the following error:

```output
[09:28:56] Error in plugin 'gulp-nuget'
Message:
    spawn ./nuget.exe EACCES
Details:
    errno: -13
    code: EACCES
    syscall: spawn ./nuget.exe
    path: ./nuget.exe
    spawnargs: pack,/Users/jimbennett/GitHub/azure-functions-templates/Build/PackageFiles/ItemTemplates.nuspec,-version,2.0.0,-outputDirectory,./.gulp-nuget,-nopackageanalysis,-noninteractive
    cmd: ./nuget.exe pack /Users/jimbennett/GitHub/azure-functions-templates/Build/PackageFiles/ItemTemplates.nuspec -version 2.0.0 -outputDirectory ./.gulp-nuget -nopackageanalysis -noninteractive
    domainThrown: true
[09:28:56] 'build-all' errored after 794 ms
```

**Comment by soninaren** [comment]
Unfortunately the template build is not cross platform. It uses Nuget.exe that would only work on a windows machine.

**Comment by jimbobbennett** [comment]
Nuget can run under Mono, but I guess the work to add this might be beyond the scope of this.

For the meanwhile, I've raised #1056 to update the README to indicate only Windows is supported to build this.

**Comment by soninaren** [comment]
Thanks for the PR. It might be better to try and remove the dependency on nuget.exe. Although it may not be that easy given that the repo needs to build dotnet templates which are nuget packages themselves.
