### ISSUE TITLE
.NET 5.0 isolated template for SignalR template has errors

### ISSUE THREAD

**Issue by vijayrkn** [Azure/azure-functions-templates#1068]
Creating on behalf of the VS customer - https://developercommunity.visualstudio.com/t/Azure-Function-for-SignalR-has-code-erro/1448794

When creating an Azure function with SignalR template in NET5, the created example marks three errors.

(1) Cannot implicitly convert type ‘System.Collections.Generic.Dictionary<string, string>’ to ‘Microsoft.Azure.Functions.Worker.Http.HttpHeadersCollection’
(2) Cannot implicitly convert type ‘string’ to ‘System.IO.Stream’
(3) Cannot create an instance of the abstract type or interface ‘HttpResponseData’

To reproduce the problem, just create an Azure functions project and add a function for SignalR. Of course, I have created the SignalR service in the portal, and it works fine.

**Comment by liliankasem** [comment]
Was able to repro this issue, will add to the host project so it can be addressed in one of our upcoming sprints

**Comment by fabiocav** [comment]
@anthonychu @cachai2 can you help with assignment here? If unclear, we can try to assign this on our end. Thanks!

**Comment by anthonychu** [comment]
Likely needs a repro to investigate further.

**Comment by liliankasem** [comment]
Here's the repro I created in December: https://github.com/liliankasem/repro-dotnet5-signalr-template

I did try recreating the issue today and didn't see any problems so this may have already been fixed since then.

**Comment by fabiocav** [comment]
@anthonychu let us know if you can engage the right folks here, otherwise; we can get this assigned

**Comment by anthonychu** [comment]
Thanks @liliankasem. I can also confirm that it seems to be working fine.

The template does need some updating so it returns a response compatible with what's expected from a negotiate endpoint, but it appears to work fine without any errors.

**Comment by liliankasem** [comment]
It appears we are no longer able to repro with the same errors so we'll close the issue. Let us know if you're still facing this problem with the latest tools.
