### ISSUE TITLE
Update Functions V4 item templates to use newest extension packages

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-templates#1097]
The templates are referencing quite old NuGet packages and need to be updated. I recommend that at a minimum, the packages reference the versions described in this breaking change:
https://github.com/Azure/Azure-Functions/issues/1987

**Comment by fabiocav** [comment]
This is in progress, on track to finish in 110.

**Comment by surgupta-msft** [comment]
Merged the PR linked with this. Closing the issue.
