### ISSUE TITLE
Error raised when creating new HttpTrigger function on CLI v4

### ISSUE THREAD

**Issue by WestDiscGolf** [Azure/azure-functions-templates#1106]
As per @anthonychu's blog post - https://techcommunity.microsoft.com/t5/apps-on-azure/announcing-azure-functions-4-0-public-preview-with-net-6-support/ba-p/2772098 - I have updated my v4 core tools.

On creating a new HttpTrigger function I receive the following error:

```
The post action 84c0da21-51c8-4541-9940-6ca19af04ee6 is not supported.
Description: Opens the function class file in the editor
```

**Steps to reproduce**

1. cd c:\temp
2. mkdir functions8
3. cd functions8
4. func init --worker-runtime dotnetIsolated
5. func new
6. select HttpTrigger from option list
7. Add name of function eg. MyFunction

**Results**
```
C:\Temp\functions8> func new
Use the up/down arrow keys to select a template:Function name: MyFunction
MyFunction
The post action 84c0da21-51c8-4541-9940-6ca19af04ee6 is not supported.
Description: Opens the function class file in the editor

The function "MyFunction" was created successfully from the "HttpTrigger" template.
```

**SDKs installed**

C:\Temp\functions8> dotnet --list-sdks
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.406 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.401 [C:\Program Files\dotnet\sdk]
6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

**Comment by anthonychu** [comment]
Thanks for reporting. @brettsam @soninaren can we suppress this message?

**Comment by brettsam** [comment]
@soninaren -- do you know where that comes from?

**Comment by soninaren** [comment]
"Post action" is something that is supported by dotnet templating engine. The action by the `post action` is going to do is "Opening a newly created file in editor". This action opens the newly created function file in editor. It is not applicate to dotnet cli (used by core tools) as there is no editor. There might be a change in dotnet templating that shows a warning if we try to invoke the post action that is unsupported in dotnet cli as opposed to ignoring it. However this should not impact template creation in anyway.

**Comment by WestDiscGolf** [comment]
@soninaren It doesn't appear to effect the creation of the function file in the limited testing I have done however it is a little concerning when you see something displayed which looks on first glance as an error. The "not supported" warning should not be outputted to the console window.

**Comment by WestDiscGolf** [comment]
Interestingly, well I thought it was, I just ran the same command in the developer terminal inside Visual Studio 2022 Preview 4.1 half expecting the post action to execute and open the newly creating function in the IDE instance but the same error occurred.

```
Use the up/down arrow keys to select a template:Function name: GetWelcome
GetWelcome
The post action 84c0da21-51c8-4541-9940-6ca19af04ee6 is not supported.
Description: Opens the function class file in the editor

The function "GetWelcome" was created successfully from the "HttpTrigger" template.
```

**Comment by soninaren** [comment]
> Interestingly, well I thought it was, I just ran the same command in the developer terminal inside Visual Studio 2022 Preview 4.1 half expecting the post action to execute and open the newly creating function in the IDE instance but the same error occurred.

This is expected. If the command was executed via dotnet cli, regardless of the kind of terminal window. 

The only time this post action actually takes effect is when it is run via the VS UI. So if you add a function to your project via VS, `right click csproj -> Add a function -> (follow wizard until function creation)`. This is when you would see the newly created function in editor.

**Comment by satvu** [comment]
Closing for now since the fix has been merged
