### ISSUE TITLE
Project Templates needed for .NET Standard 2.0 isolated worker

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-templates#1186]
We need new .NET project templates for .NET Standard 2.0 in an isolated worker model. These should not go directly into the tooling feed initially.

Ideally, these should largely align with templates for isolated in general. The main difference would be the TFM specified in the .csproj, I think.

**Comment by fabiocav** [comment]
This was the templates issue tracking the work: https://github.com/Azure/azure-functions-templates/issues/1229

The changes have been merged. Closing as resolved.
