### ISSUE TITLE
Missing resource `cosmosDBIn_leaseCollectionName_help`

### ISSUE THREAD

**Issue by alexweininger** [Azure/azure-functions-templates#1342]
`cosmosDBIn_leaseCollectionName_help` resource is missing from all but the cs-CZ resources file. This resource is referenced in the `cosmosDBTrigger` binding.

<img width="1119" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/12476526/222223256-a68236ab-5d1a-4b71-ac05-81f4b059e7a9.png">

**Comment by soninaren** [comment]
Fixed in here
https://github.com/Azure/azure-functions-templates/commit/bf9c9f4d8bc8ae9dbb3323eb9df17368f798bd28
