### ISSUE TITLE
Consider changing EventHub templates to use Arrays

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-templates#293]
@MikeStall Has been doing some throughput analysis on EventHubs and has found that the optimal way to receive events in high throughput scenarios is to bind to an array of events (batching) rather than the current default of singleton. We want to have the right default in place.

For C#/F# we can simply bind to an array. Node doesn't support binding to arrays yet for triggers, but we'll be addressing that (see [this issue](https://github.com/Azure/azure-webjobs-sdk-script/issues/618)).

**Comment by lindydonna** [comment]
Work with @christopheranderson on the work

**Comment by mathewc** [comment]
@MikeStall What do you think - should we update our templates to default to using arrays vs. singleton? It's not just a perf consideration, it's also what we think will be most commonly wanted by users - do they want arrays or singletons?

**Comment by paulbatum** [comment]
I'm deferring this decision while we continue work on optimizing high throughput Event Hub scenarios.

**Comment by tohling** [comment]
We should fix this sooner. I have seen instances where customers use the Portal template to create an Node.js EventHub-Triggered Function that processes one event at a time and the Function never completes.  Log entries would show only "Function started(...)" but no corresponding "Function completed(...)".  Once the customer switched to processing in batches, the issue went away.  

This very recent issue was opened by another customer that exhibits the same behavior for Node.js EventHub-Triggered Functions:
https://github.com/Azure/azure-webjobs-sdk-script/issues/1386#issuecomment-293372407

**Comment by paulbatum** [comment]
I was the bottleneck on this, sorry. Once we switch to batching, we need to provide an error handling example in the template, otherwise people will naturally lose data without any attempt at processing it. So you are correct we need to combine with #705. 

Here is what I have so far. I've tested this, seems to work well:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Azure.EventHubs;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace FunctionApp12
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run(
            [EventHubTrigger("scratch", Connection = "EventsConnectionString")] EventData[] events, 
            ILogger log)
        {                        
            var exceptions = new List<Exception>();

            foreach (EventData eventData in events)
            {
                try
                {                    
                    var messageBody = Encoding.UTF8.GetString(eventData.Body.Array, eventData.Body.Offset, eventData.Body.Count);
                    log.LogInformation($"C# Event Hub trigger function processed a message: {messageBody}");
                    
                }
                catch (Exception e)
                {                    
                    // We need to keep processing the rest of the batch - capture this exception and continue                    
                    exceptions.Add(e);
                }
            }

            if (exceptions.Count > 1)
                throw new AggregateException(exceptions);

            if (exceptions.Count == 1)
                throw exceptions.Single();
        }
    }
}
```

**Comment by paulbatum** [comment]
I need to make some tweaks to make it clearer that the message itself needs to be captured somewhere so it can be retried. Will send another revision.

**Comment by paulbatum** [comment]
I should add that I think this template should probably be switched from string to EventData so that we can show users how to extract a string from EventData since its not obvious. I did this in the example above.

**Comment by paulbatum** [comment]
Instead of pasting inline I'm using a gist (did not want to create a PR because I would have to make the template also support csx)
https://gist.github.com/paulbatum/ebdca12ba4b95700f1cc0e08aa213252

**Comment by soninaren** [comment]
I can take this one and release it along the durable template update i will be pushing in the current release.

**Comment by paulbatum** [comment]
The gist has been updated based on feedback. @soninaren can you take this over and handle the csx case?
