### ISSUE TITLE
Unable to install python module azure-datalake-store - error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

### ISSUE THREAD

**Issue by HavardAustefjord** [Azure/azure-functions-templates#548]
I would like to reach my azure data lake files from my Azure Function App in Python. Following the steps in the tutorial at https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-get-started-python I stopped at: python -m pip install azure-datalake-store 
with the following error msg from kudu debug console:
<! Start msg from console
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying scandir.py -> build\lib.win32-2.7
    running build_ext
    building '_scandir' extension
    error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
    
    ----------------------------------------
Command "D:\home\site\tools\python.exe -u -c "import setuptools, tokenize;__file__='d:\\local\\temp\\pip-build-s4qkdo\\scandir\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record d:\local\temp\pip-zxzoyq-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in d:\local\temp\pip-build-s4qkdo\scandir\
End Msg >

I first tried this on my Python 2.7.13 64bit installation and thought it was not supported on 64bit. I then tried the 2.7.13x86 version and got the same result. 

When trying to install Microsoft Visual C++ 9.0 from http://aka.ms/vcpython27 I get msg that I'm not allowed to do this operation.

Is there any fix for this or any way to get the azure data lake packages working on azure function?

Thanks!

**Comment by JensMadsen** [comment]
I have a similar problem

**Comment by paulbatum** [comment]
Not a template issue. If its still a problem reopen in https://github.com/Azure/azure-functions
