### ISSUE TITLE
Mark optional attributes as optional for cosmosDB trigger documentation

### ISSUE THREAD

**Issue by jocawtho** [Azure/azure-functions-templates#549]
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Functions.Templates/Documentation/cosmosDBTrigger.md
Only type, name, direction, databaseName, and collectionName are required. The rest can be marked as optional. 
Also lets include the app setting we look for for the connection string here so if people want to leave out the connection setting we can be sure they know that the connection string should be "AzureWebJobsDocumentDBConnectionStringName"

**Comment by soninaren** [comment]
https://github.com/Azure/azure-functions-templates/commit/2ddb8863bb41cb4ebfacea95e6dd7a4a52aa5c20
https://github.com/Azure/azure-functions-templates/commit/cc592ca72337f9176f15cca9f16a180b2fa3c0a9
