### ISSUE TITLE
Advanced editor input binding validation issue

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-templates#553]
For a C# function, you can bind an input to a CloudQueue. We don't expose this as a regular input binding, because it's an advanced scenario, and users don't really do it often.

So you have to go to the advanced editor to set it up. In doing so, I found a strange squiggly error (below). I should be able to enter valid values here. Also, I'm not sure where its getting "ServiceBusTrigger".

![image](https://user-images.githubusercontent.com/1056548/29949935-28d256f6-8e6d-11e7-8a79-edd767ff1acd.png)

**Comment by paulbatum** [comment]
@mathewc Can you verify this still repros?

**Comment by paulbatum** [comment]
No followup, old issue, closing
