### ISSUE TITLE
META: Rename repo to azure-functions-templates

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-templates#596]
This repo is mostly about Functions, and very little about it is applicable to Azure WebJobs SDK. Would it make sense to rename this repo so we don't have to explain our naming scheme/etc. and people can find it organically?

**Comment by paulbatum** [comment]
I agree, this is a better name. I will wait until @soninaren is back from vacation before making the change to make sure there arent any unexpected issues.

**Comment by soninaren** [comment]
This is done
