### ISSUE TITLE
Change display names for VS Tools

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-templates#599]
A number of customers get stuck by some of the display names on creating a new function.  "Connection" for example could potentially be more clear by naming it "Connection Key Name", "Path" for Event Hub should be called "Event Hub Name", etc.

**Comment by paulbatum** [comment]
@jeffhollan Are you going to come up with a full list of proposed display name changes?

**Comment by jeffhollan** [comment]
Yes thanks for ping. was looking for this item the other day. Will open a PR this week or next

**Comment by soninaren** [comment]
This is done
