### ISSUE TITLE
Azure Fucntion Python : Failure after upgrading to python 3

### ISSUE THREAD

**Issue by vincentJolivet** [Azure/azure-functions-templates#616]
I am following https://prmadi.com/running-python-code-on-azure-functions-app/
and keep on having failure after the upgrade.
If I empty d:\home\site\tools than I revert back to 2.7.8 version and the Azure function is working.

I've tried 3.5, 3.6 all failed.

Vincent

**Comment by paulbatum** [comment]
Not a templates issue.
