### ISSUE TITLE
Update F# templates to be compiled libraries

### ISSUE THREAD

**Issue by cartermp** [Azure/azure-functions-templates#627]
F# has full support in the .NET Core SDK, so we can start to migrate the F# templates [as defined in the README](https://github.com/Azure/azure-functions-templates#adding-new-templates-for-visual-studio-only-c-only).  The scope of the work:

* Convert each of the templates which use F# scripts to be F# projects with the same code, just in an F# source file
* Add/update template metadata the same way that C# is done
* We can do this for both v1 and v2, since F# should be supported in both places

**Comment by cartermp** [comment]
cc @dsyme

**Comment by dsyme** [comment]
@cartermp @soninaren Am happy to help with this, e.g. reviewing a PR.  Let me know the plan?

**Comment by cartermp** [comment]
@dsyme A few things we'll have to do:

* Work with @soninaren to build out an equivalent [`Project Template`](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/ProjectTemplate) for F#, since the current one is only C#.
* `Microsoft.NET.Sdk.Functions` reads metadata from the C# templates to generate the `function.json` file, so we'll need to ensure that this works for F# templates as well.
* Supply a sample project using the new .NET Core SDK-based project files, such as from [this excellent blog post](https://mikhail.io/2017/12/precompiled-azure-functions-in-fsharp/)

**Comment by cartermp** [comment]
Actually @soninaren I just realized that the linked blog post has a link to a project that has a sample F# function using .NET Core SDK-based tools that works today: https://github.com/mikhailshilkov/azure-functions-fsharp-examples/tree/master/6-precompiled-timer

It looks like we'd need to add attributes [like in the C# equivalent](https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/TimerTrigger-CSharp/TimerTriggerCSharp.cs#L15) though, yes? So the code would look something like this:

```fsharp
namespace HelloFunctions

open Microsoft.Azure.WebJobs
open Microsoft.Azure.WebJobs.Host

module Say =
    [<FunctionaName("TimerTriggerFSharp")>]
    let hello (TimerTrigger("ScheduleValue")] timer: TimerInfo, log: TraceWriter) =
        let now = System.DateTime.Now.ToString("HH:mm:ss dd/MM/yyyy")
        log.Info (sprintf "Function ran at %s" now)
```

**Comment by soninaren** [comment]
This is great. I guess we have the first part figured out. We definitely need to add c# equivalent attributes here.
The second part is that we would also need to make sure only f# templates get listed in the context menu when you select _Add -> New Item -> Azure Function_

**Comment by cartermp** [comment]
cc @tihan, @pilchie, and @mlorbetske for this:

> The second part is that we would also need to make sure only F# templates get listed in the context menu when you select Add -> New Item -> Azure Function

**Comment by cartermp** [comment]
Hey @soninaren I'm trying to put together a sample template that would work for the Blob Trigger.

This commit is what my what it looks like: https://github.com/cartermp/azure-webjobs-sdk-templates/commit/67f52c5fc4a75a395ea99d4b1786381829b211b6

The issue I'm having is building a template against a project file, which this repo does not have for F#. The F# equivalent of what C# project file is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BlobTriggerFSharp.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
  <Content Include="host.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Include="local.settings.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  </Content>
</ItemGroup>

</Project>
```

Is this enough information for you to start porting? I'm more than happy to book some time in-person to walk through porting a few of them one-by-one. The F# code is pretty straightforward; we'll just need to get things set up so that we can port one over, test the template, and iterate from there on other templates.

**Comment by mikhailshilkov** [comment]
@cartermp I played with your suggested change and created a nuget package from it.

To try it out:
1. Download the file from https://www.myget.org/F/azurefunctions-templates-fsharp/api/v2/package/Azure.Functions.Templates.FSharp/1.0.0
2. Run 
`dotnet new -i "Azure.Functions.Templates.FSharp.1.0.0.nupkg"`
3. Create a new Azure Functions F# project:
`dotnet new "Azure Functions" -lang F#`
4. Add a blob triggered function to it:
`dotnet new "BlobTrigger" -lang F#`

The last command is NOT adding the following lines to `fsproj` though:
```
<ItemGroup>
   <Compile Include="BlobTriggerFSharp.fs" />
</ItemGroup>
```

Any idea how this can be done?

If this is done, can we just start adding the templates, or what else do  you expect from @soninaren ?

**Comment by soninaren** [comment]
Have added the F# Project template to the build 
https://github.com/Azure/azure-functions-templates/commit/103bf250a92119839a679be7f1c3c29db92e3eb4

**Comment by mikhailshilkov** [comment]
Does anybody have a status of this issue and a plan? There is #738 which exists for months and touches 150+ files. Why not merge something simple like 1 HTTP and 1 Timer template and then get going from there?

**Comment by jeffhollan** [comment]
Thanks for the ping. @soninaren who is likely best person to help here is heads down on removing the .NET SDK requirement to use extensions in other languages but let me flag this so we can discuss what is required to at least get the CLI create working

**Comment by Angr1st** [comment]
Hopefully we can finally get this moving forward. Would make the life of Fsharp devs a little easier.

**Comment by aaronpowell** [comment]
@jeffhollan @soninaren let me know if there's anything I can do from the CDA team perspective to help 😁

**Comment by cartermp** [comment]
This is now in. Still plenty of work left to get to parity, but it's progress! 🙂

**Comment by soninaren** [comment]
@cartermp have merged you F# templates PR into the templates repo here https://github.com/Azure/azure-functions-templates/commit/32ad34d09ea3208659b8db0b1568e5c2212cceaa. Will add those template to the current template release .

**Comment by soninaren** [comment]
Closing this one as it has been deployed to nuget
