### ISSUE TITLE
azure http trigger function rest api call timeout

### ISSUE THREAD

**Issue by govjobss** [Azure/azure-functions-templates#629]
I am using  azure powershell http trigger function and trying to trigger it using invoke-restmethod ps command but it is getting internal server error after 4 min at the same time i can see the function running on azure portal.

ps - i am using app service plan ands also tried functionTimeout in host.json file

**Comment by paulbatum** [comment]
This isn't a template issue. Please file an issue in https://github.com/Azure/azure-functions-host and follow the template (we need investigative information to be able to help).
