### ISSUE TITLE
Cannot find resized images

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#630]
Visual Studio version: Visual Studio 2017 Enterprise 15.5.6 (Release)
Azure Functions Tools version: 15.0.40108.0
Functions NuGet package: 1.0.8

The ImageResizer template can be triggered successfully. But no output files can be found in the target blob containers.

**Comment by paulbatum** [comment]
@soninaren any known issues with this template? Can you follow up with simon?

**Comment by soninaren** [comment]
No known issues, Will try to repro and follow up with simon

**Comment by SimonGuo009** [comment]
This issue cannot be reproduced in the CLI release test today on 02/28/2018. So I'm going to close it.
