### ISSUE TITLE
Function can't be totally deleted before rebuild the function app

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#631]
Visual Studio version: Visual Studio 2017 Enterprise 15.5.6 (Release)
Azure Functions Tools version: 15.0.40108.0
Functions NuGet package: 1.0.8

**Repro steps:**
1. Create a function app and a timertrigger function in VS. Verify timer is working.
2. Delete timer function from the solution explorer. 
3. Run app again and verify timer is still working.
4. Browse the local directory of the functions, verify the folder for timerTrigger function still exists, including its functions.json file.
5. Rebuild the function app. Verify the timer trigger won't work again. And the corresponding directory disappeared.

Please refer to the attached snapshot:
![vs_bug_cannottotallydeletefunction](https://user-images.githubusercontent.com/18321627/36025475-1ab1ef94-0d8b-11e8-8262-8f857cd97361.png)

**Comment by ahmelsayed** [comment]
@vijayrkn this seems like a general VS bug. Deleting a file from a csproj doesn't trigger a rebuild. MSBuild says that the build is up to date. 

I can repro this with just a regular .NETStandard class library in VS 15.5.6 

Repro steps:

1. Create a .NETStandard class library
2. right click on the project and change debug to "executable" and put any random exe in there
3. Add Class1 and Class2
4. CTRL + F5 -> builds correctly
5. Delete Class2
6. CTRL + F5 -> "build is up to date"
5. CTRL _

**Comment by vijayrkn** [comment]
@ahmelsayed - Since this issue happens outside of the function app and on a simple netstandard app, can you please move this bug to https://github.com/dotnet/project-system

**Comment by ahmelsayed** [comment]
thanks @vijayrkn! I opened https://github.com/dotnet/project-system/issues/3245
