### ISSUE TITLE
Rebuild operation will clean the .git folder in functions directory

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#632]
Visual Studio version: Visual Studio 2017 Enterprise 15.5.6 (Release)
Azure Functions Tools version: 15.0.40108.0
Functions NuGet package: 1.0.8

**Description:**
Init git repo for local function app, then bind it to Azure. There will be a .git folder to keep the source control related files. 
But if you rebuild the function app in VS, the .git folder will disappear.

**Comment by ahmelsayed** [comment]
are you initializing the git repo in the output directory? I tried to init the repo in the sources directory and it was fine. It does get deleted if you init it in the output dir, but that's just standard msbuild behavior I believe

**Comment by paulbatum** [comment]
@SimonGuo009 I'm assuming the git repo was in the output directory in which case this behavior is expected. Closing.. reopen if that was not the case.
