### ISSUE TITLE
PowerShell in Azure Functions

### ISSUE THREAD

**Issue by MotiBa** [Azure/azure-functions-templates#636]
Per my understanding the app settings are exposed to the Azure functions as environment variables, so we can reference them in the script as $env:VariableName.

But it doesn't work, when I try to access the $env:VariableName it doesn't exist.

**Comment by pragnagopa** [comment]
I cannot repro this. Try this to see all the environment variables you have:

write-Output 'Getting environment variables'
$result = ls env: | out-string
write-output $result

Referring to environment variable:  $env:<variablename> should work. I am closing this issue. Please reactive if you still issues.
