### ISSUE TITLE
Failed to trigger QueueTrigger-C#(V2) after pushed to azure

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#637]
**Portal Environment:**	  https://ms.portal.azure.com
**Browser:**	English/Chrome
**Visual Studio:**	2017 Enterprise 15.5.6
**Azure Function Tools:** 15.0.40108.0
**CLI**: https://ci.appveyor.com/project/appsvc/azure-functions-cli/branch/v1.x/artifacts (x86)

**Expected Result:** 
After pushed to azure, function should trigger-able and the text in the queue message should appear in the Logs Section.

**Actual Result:**
There are no traced messages in the Logs.

**Repro steps:**
1. Create and run a QueueTrigger-C#(V2) in VS, verify it succeeded.
2. Deploy it into Azure environment.
3. Add the Queue connection string under Application settings. 
4. Trigger the function via Storage Explorer and verify there are no trigger messages in Logs.

**Comment by mathewc** [comment]
Does this still repro in the latest release bits? This issue is pretty old - closing. Please reopen as needed.
