### ISSUE TITLE
Should include "LeaseCollection" binding box in new "Cosmos DB Trigger" function dialog

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#638]
**Portal Environment:**	 https://ms.portal.azure.com
**Browser:**	English/Chrome
**Visual Studio:**	2017 Enterprise 15.5.6
**Azure Function Tools:** 15.0.40108.0
**CLI:** https://ci.appveyor.com/project/appsvc/azure-functions-cli/branch/v1.x/artifacts (x86)

**Expected:**
Required bindings should all have related textbox in the creating dialog.
**Actual:**
Lease Collection binding do not have a textbox in New "Cosmos DB Trigger" function dialog.

Please refer to snapshot:
![missingbindingtextbox1](https://user-images.githubusercontent.com/18321627/36843299-6aa18af8-1d46-11e8-9334-a92a8c6d9264.png)

**Comment by pragnagopa** [comment]
This is by design. LeaseCollectionName is an optional value. We only expose required settings in the UI.
Adding @soninaren to confirm.

**Comment by soninaren** [comment]
this is by design
