### ISSUE TITLE
Should warn users when they add new function with existing function name

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#639]
**Portal Environment:**	 https://ms.portal.azure.com
**Browser:**	English/Chrome
**Visual Studio:**	2017 Enterprise 15.5.6
**Azure Function Tools:** 15.0.40108.0
**CLI:** https://ci.appveyor.com/project/appsvc/azure-functions-cli/branch/v1.x/artifacts (x86)

**Expected**:
When users are trying to add a new function with existing function name, VS should manage to warn them.
**Actual**:
When they are trying to do so, filled all binding data then hit Create, nothing happened.

**Comment by pragnagopa** [comment]
This is a VS tooling improvement issue. Not related to templates. 
@soninaren - where do we track these issues?

**Comment by pragnagopa** [comment]
Discussed with @soninaren. For now closing this issue as won't fix. We will revisit this if we see more customers running into this error
