### ISSUE TITLE
Python Templates

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-templates#646]
Similar to C# and JavaScript, we want to provide function templates in Python for commonly used trigger scenarios - 

- [x] Http Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/HttpTrigger-JavaScript))

- [x] Timer Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/TimerTrigger-JavaScript))

- [x] Blob Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/BlobTrigger-JavaScript))

- [x] Queue Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/QueueTrigger-JavaScript))

- [x] Event Grid Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/EventGridTrigger-JavaScript))

- [x] Cosmos DB Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/CosmosDBTrigger-JavaScript))

- [x] Event Hub Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/EventHubTrigger-JavaScript))

- [ ] Service Bus Queue Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/ServiceBusQueueTrigger-JavaScript))

- [ ] Service Bus Topic Trigger ([JS example](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/ServiceBusTopicTrigger-JavaScript))

**Comment by asavaritayal** [comment]
\cc @elprans

**Comment by elprans** [comment]
PR: https://github.com/Azure/azure-functions-templates/pull/644

**Comment by paulbatum** [comment]
@asavaritayal I see the linked PR for adding the service bus template, and that was the last missing item tracked in the list above. Can this be closed now?

**Comment by asavaritayal** [comment]
> I see the linked PR for adding the service bus template, and that was the last missing item tracked in the list above. Can this be closed now?

Yes, closing the issue as this is now done.
