### ISSUE TITLE
Colons required in the log string of the JavaScript templates

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-templates#656]
_From @SimonGuo009 on April 2, 2018 10:7_

**Environment URL:**   https://functions-staging.azure.com 
**Corresponding Ibiza URL:**   https://portal.azure.com?websitesextension_ext=appsvc.env=stage
**App runtime version:**  1.0.11612.0 (~1)
**Proxy runtime version:**   2.0.11651.0 (beta)
**Browser:** Chrome

**Description:**
Some of the JavaScript templates do not have colon at the end of the log strings. As a result, the log prints "2018-04-02T07:13:22.558 [Info] Processed message Test Message" instead of 2018-04-02T07:13:22.558 [Info] Processed message : Test Message

**Related templates:**
EventHubTriggerJS, QueueTriggerJS, ServiceBusQueueTriggerJS, ServiceBusTopicJS

Please refer to snapshot:
![bug7_missingcolonmark](https://user-images.githubusercontent.com/18321627/38192672-891246f0-365d-11e8-8d65-3a25d087d046.png)

_Copied from original issue: Azure/azure-functions-ux#2510_

**Comment by soninaren** [comment]
https://github.com/Azure/azure-functions-templates/commit/ec2ee4452091e148f76cd7538a39f23e5c46e920
