### ISSUE TITLE
Update the webjobs pacakge dependency on the Eventgrid extension package for v1

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-templates#659]
Microsoft.Azure.WebJobs.Extensions.EventGrid right now refers Microsoft.Azure.WebJobs 2.1.0, we need to update this to Microsoft.Azure.WebJobs 2.2.0. 
This is to by pass compile time VS bug when referring Microsoft.Azure.WebJobs.Extensions.EventGrid version 1.0.0-beta3

**Comment by brettsam** [comment]
@watashiSHUN -- can this be closed now that it's been merged?
