### ISSUE TITLE
"JsonSerialization.cs not found" issue occurs when running V1 storage queue template

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#661]
**Visual Studio version:** Visual Studio 2017 Enterprise 15.6.4 (Release)
**Azure Functions Tools version:** 15.0.40403.0
**CLI:** 2.0.1-beta.25

Please refer to the snapshot:
![bug1_storagequeuebug](https://user-images.githubusercontent.com/18321627/38308937-1d84cfc8-3808-11e8-826f-959f6c1ea6fa.png)

**Repro steps:**
1. Create a V1 storage queue template in VS.
2. Run it locally then trigger it, verify it was paused and the page in attached snapshot appear.
3. Click continue then the function was successfully triggered.
4. Later when trying to trigger this function locally again, nothing happens.

**Comment by paulbatum** [comment]
@SimonGuo009 is this part of your bug report correct?

> CLI: 2.0.1-beta.25

Because this is a V1 template, the CLI version should have been `Version=1.0.11612.0`

**Comment by soninaren** [comment]
this was validated and closed.
