### ISSUE TITLE
V2 service bus reference do not include Microsoft.ServiceBus namespace

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#662]
**Visual Studio version:** Visual Studio 2017 Enterprise 15.6.4 (Release)
**Azure Functions Tools version:** 15.0.40403.0
**CLI:** 2.0.1-beta.25

**Expected result:**
When a new function is created, it should be good to go.
**Actual result:**
Service Bus namespace cannot be found in the reference.

Please refer to the snapshot:
![bug2_servicebusreference](https://user-images.githubusercontent.com/18321627/38309085-8db5edcc-3808-11e8-8046-b54d197303eb.png)

PS: Push the functions to azure, they will work fine.

**Comment by paulbatum** [comment]
I think the using statement should be `using Microsoft.Azure.ServiceBus;` for V2

**Comment by soninaren** [comment]
Fixed in here. Have removed the using statement since it is not being used.
https://github.com/Azure/azure-functions-templates/commit/0d0a0ac5c13d5d77128c394af51b01c40423d063
