### ISSUE TITLE
Update C#/F# samples to use ILogger

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-templates#667]
At a minimum, we need to update the V2 templates to use ILogger instead of TraceWriter.

We should consider doing the same for the V1 templates too, but only if/when this is fixed:
https://github.com/Azure/azure-functions-core-tools/issues/130

**Comment by paulbatum** [comment]
@jeffhollan Do you plan on working on this in the next two weeks? If so it should go into Sprint 26.

**Comment by jeffhollan** [comment]
Created branch today and started on it. Will have PR by end of week
