### ISSUE TITLE
Azure function failed to deploy with the error ERROR_CONNECTION_TERMINATED

### ISSUE THREAD

**Issue by njangir2** [Azure/azure-functions-templates#677]
## Issue Description
I am trying to deploy the azure function using visual studio and getting the error: Web deployment task failed (Complete error logs are given below).
I have followed all the steps mentioned in the article http://techgenix.com/video-publish-azure-functions-azure-using-visual-studio-tools-azure-functions/ but still facing the issue.
Please help me as I have spent a lot of time on this issue and didn't get any solution.

Just to add a note here fiddler was not running on my system when I tried the deploy the function.
### Error logs

1>------ Build started: Project: TestFunction, Configuration: Release Any CPU ------
1>TestFunction -> C:\Repo\TestFunction\TestFunction\bin\Release\net461\bin\TestFunction.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
  Publish Started
  TestFunction -> C:\Repo\TestFunction\TestFunction\bin\Release\net461\bin\TestFunction.dll
  TestFunction -> C:\Repo\TestFunction\TestFunction\obj\Release\net461\PubTmp\Out\
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web deployment task failed. (Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.) [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :  [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED. [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Root element is missing. [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
  Publish failed to deploy.

**Comment by soninaren** [comment]
Moved to the correct repo
https://github.com/Azure/Azure-Functions/issues/792

**Comment by lymedo** [comment]
Getting the same issue publishing from Visual Studio with a V2 function.
Created a new HTTP function, tested it locally and attempted publish.

`Message:
Publish has encountered an error.
Publishing failed.
A diagnositic log has been writter to the following location: "C:\Users\user\AppData\Local\tmpB1F0.tmp"

Output:
Web deployment task failed. (Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.
Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.
Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 550.

Diagnostics Log (tmpB1F0.tmp):
06/05/2019 11:32:37
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__183.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

===================`
