### ISSUE TITLE
Event Hub & IoT Hub functions cannot be executed successfully after pushed to Azure

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-functions-templates#678]
**Portal Environment**:  https://ms.portal.azure.com
**Visual Studio**:  2017 Enterprise 15.6.7
**VSIX**: \\vwdbuild01\drops\WTA\AzureFunctions-Dev15-OOB.Nightly\Dev15\2018-04-25_b6062\Release\Signed\VSIX\enu\Microsoft.VisualStudio.Web.AzureFunctions.vsix
**Azure Function Tools:**  15.0.40425.0
**Runtime:** V2 beta
**Browser:**  English/Chrome

**Expected result:**
Those functions should work well after pushed to azure.
	
**Actual result:**
Those functions cannot be executed successfully. If we tried to trigger them, they will get simple error message like below

_2018-04-28T11:00:01.699 [Information] Executing 'EventHub' (Reason='This function was programmatically called via the host APIs.', Id=e5c83aaa-e7f0-46a3-a2d2-7648324b4608)
2018-04-28T11:00:01.792 [Error] Executed 'EventHub' (Failed, Id=e5c83aaa-e7f0-46a3-a2d2-7648324b4608)_

**Comment by soninaren** [comment]
Was not able to repro. Can you try again? Please reopen if you can repro.
