### ISSUE TITLE
Creating a V2 project does not set language

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-templates#685]
This is related to https://github.com/Azure/azure-functions-host/issues/2668, but essentially when creating a Function project in VS, ~~`FUNCTIONS_LANGUAGE`~~ is not set in the local.settings.config, so error messages appear on F5.

> Unable to configure java worker. Could not find JAVA_HOME app setting.
> Could not configure language worker Java.

**UPDATE:**
Combing through old PRs has its disadvantages. The setting name was changed. The app setting needs to be added like so.

```javascript
{
  "Values": {
    ...
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"       <- This line
  }
}
```

**Comment by pragnagopa** [comment]
@MisinformedDNA - Yes. Setting name was changed to FUNCTIONS_WORKER_RUNTIME. Is this still an issue? Are you able to restrict language supported in a function app?

**Comment by MisinformedDNA** [comment]
I'm not entirely sure what just upgraded, but I just reloaded VS and re-ran the Function project and something upgraded. I thought I saw CLI and 2.1, but the latest Azure Functions CLI is still at [2.0.1-beta.26](https://github.com/Azure/azure-functions-core-tools/releases), so I'm not sure what it was. Maybe it was dotnet CLI 2.1?

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.300-rc1-008673
>  Commit:    f5e3ddbe73
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\
> 
> Host (useful for support):
>   Version: 2.2.0-preview1-26424-02
>   Commit:  286ba8868b

In any case, it's now working for me. However, I still think this line should be set by default in .NET project templates. Or set in the background a part of the `Microsoft.NET.Sdk.Functions` package`. It's a bad user experience when you load up a fresh project and you immediately get warnings or errors.

**Comment by pragnagopa** [comment]
Adding this setting FUNCTIONS_WORKER_RUNTIME is first part of the changes to support restricting language in a function app. Tooling changes will be coming soon. Closing this for now.

**Comment by paulbatum** [comment]
Yes to clarify, the java related error has been fixed in the latest release, and right now setting the worker runtime is not required.

**Comment by MisinformedDNA** [comment]
@paulbatum Awesome! Glad to see the progress. However, I'm seeing unexpected results. When `"FUNCTIONS_WORKER_RUNTIME": "dotnet"` is set, I get the message 

> FUNCTIONS_WORKER_RUNTIME is specified, only dotnet will be enabled

But when I remove that setting, I get:

> Loading all the worker providers from the default workers directory: C:\Users\50587\AppData\Local\AzureFunctionsTools\Releases\2.1.0\cli\workers
> Found worker config: C:\Users\50587\AppData\Local\AzureFunctionsTools\Releases\2.1.0\cli\workers\python\worker.config.json
> Will load worker provider for language: python

There are a few issues here:
 1. Why is it loading the worker provider for python instead of dotnet?
 2. Why is `dotnet` not listed as a worker provider?
 3. Why does it say that it is "loading all the worker providers" when it only loads one, and I clearly have 3 or 4 available (not that I want them to run, but the messaging seems wrong)

![image](https://user-images.githubusercontent.com/1784452/40383129-bb1195f4-5dc5-11e8-9740-669889b004fd.png)

**Comment by paulbatum** [comment]
Short answer - its work in progress. I would not worry about it right now. You should be able to ignore this setting, ignore the worker output, and proceed with using C# functions as you would.

**Comment by MisinformedDNA** [comment]
Cool. Thanks for your help!
