### ISSUE TITLE
Add CosmosDB Python template to the CLI feed

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-templates#691]
https://github.com/Azure/azure-functions-templates/pull/679

**Comment by pragnagopa** [comment]
@soninaren - Let us know if this is not the right place to track this issue.

**Comment by soninaren** [comment]
@asavaritayal Do you need the cosmosDB template to show up in portal or CLI?

**Comment by soninaren** [comment]
This is complete. Cosmos db-python is part of the package, https://functionscdn.azureedge.net/public/TemplatesApi/2.0.0-beta-10205.zip
