### ISSUE TITLE
eventgrid sample data should be standardized

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/azure-functions-templates#697]
[single quote is not valid json](https://stackoverflow.com/a/2275428/1831108) 
https://github.com/Azure/azure-functions-templates/blob/48c0fc713a9c540df6d07dda279818b858c39efb/Functions.Templates/Templates/EventGridTrigger-CSharp/sample.dat#L2-L16
and in the test data, there's a mix usage of single quote and double quote:
https://github.com/Azure/azure-functions-templates/blob/48c0fc713a9c540df6d07dda279818b858c39efb/Functions.Templates/Templates/EventGridTrigger-CSharp/sample.dat#L16-L18

**Comment by soninaren** [comment]
#697
