### ISSUE TITLE
Reflect the Cosmos DB template for func new in Python

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-templates#699]
_From @asavaritayal on May 12, 2018 23:28_

https://github.com/Azure/azure-functions-templates/pull/679

_Copied from original issue: Azure/azure-functions-core-tools#467_

**Comment by ahmelsayed** [comment]
@soninaren  that template is still not in `templateApiZip`. I'll move this issue to the template repo. Feel free to open another one here once that's updated.

**Comment by soninaren** [comment]
Have updated templateApi Zip. for the v2-prerelease tag
 https://functionscdn.azureedge.net/public/TemplatesApi/2.0.0-beta-10205.zip
