### ISSUE TITLE
Error handling for EventHub templates

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-templates#705]
Until https://github.com/Azure/azure-webjobs-sdk/issues/1597 is addressed, it's the responsibility of user code to handle event failures, since the runtime will checkpoint regardless of success/failure of the function invocation.

We should update the EH templates with error handling + guidance, indicating that logging/persistence of failed events is the responsibility of the user.

**Comment by fabiocav** [comment]
@paulbatum moving this to 43. Let me know if you want me to change that.

**Comment by fabiocav** [comment]
Was this completed with the change here? 
https://github.com/Azure/azure-functions-templates/issues/293

@soninaren

**Comment by soninaren** [comment]
@fabiocav Yes looks like it has been handled with the template update.
