### ISSUE TITLE
Functions V2 Templates

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-functions-templates#714]
- Short Name should be lowercase, cross-platform "play nice"; .NET Core Short Names are all lowercase
- Consider using namespace type feature for short name. Having a template named `http` could be confusing as templates grow in quantity. Perhaps `func.http`, `func.blob`
- `DurableFunctionsOrchestration` is not "short"
- `dotnet new "Azure Functions"` is easily mis-typed, rename to `AzureFunctions`

Proposing these features prior to PR.

@jeffhollan

**Comment by soninaren** [comment]
Fixed in this commit 
https://github.com/Azure/azure-functions-templates/commit/2e82f02ec24d9e95a694dca6a9f7a0829f7bed35
