### ISSUE TITLE
Improve Event Hub name UI help

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-templates#715]
Event Hub bindings allow the hub name to be specified either via the connection string or via a separate hub name value (see image below). At runtime, any hub name value in the connection string will take precedence.

This produces customer confusion. I recommend we update the [help text](https://github.com/Azure/azure-functions-templates/blob/81bfd5cf6cda34b5269d13dfcfd1042530d6bd0f/Functions.Templates/Resources/Resources.resx#L138) for the various hub name controls. Same goes for input bindings as well.

![image](https://user-images.githubusercontent.com/1056548/43412818-3ba880d0-93e3-11e8-83a2-c087a981c6f4.png)

**Comment by ggailey777** [comment]
We should also update this in the Event Hub binding docs as well ([1289403](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1289403))

**Comment by soninaren** [comment]
Adding related portal issue..
We have opened an issue in portal to not append eventhub name when selecting through the wizard.

https://github.com/Azure/azure-functions-ux/issues/2735
https://msazure.visualstudio.com/Antares/_workitems/edit/3124678

**Comment by fabiocav** [comment]
Closing this as it is being tracked by the portal team.
