### ISSUE TITLE
Mandatory properties missing from function.json

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-templates#726]
Properties present in the function.json for each template are only subset of required properties. This is because the rest of the properties are listed in the "userPrompt" of the metadata.json file. The portal consumes metadata.json and populates the rest of properties by prompting the user. We need to do that for templates for all languages.

- Sample commit: 
https://github.com/Azure/azure-functions-templates/commit/ee5ebd1513833417287732fb253154671a2062d9

Related metadata.json file: 
- https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/CosmosDBTrigger-CSharp/metadata.json#L12-L17

Languages:
- [ ] Python
- [ ] C#
- [ ] JavaScript

**Comment by pragnagopa** [comment]
@asavaritayal  - Can you please follow up with @elprans to get the python templates updated?

**Comment by soninaren** [comment]
@mhoeger Can you take care of JS templates?

**Comment by soninaren** [comment]
Turns out only cosmosdb was affected by this
https://github.com/Azure/azure-functions-templates/commit/c7826a5dafd2dcb31ab439a6e55553b0f1d423ec
