### ISSUE TITLE
No template for creating EventHub trigger locally

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-templates#732]
_From @jsnikhil on August 29, 2018 0:25_

Trying to create a new function locally, and I don't see an option to create a EventHub trigger function. Is this expected?

```
$ func --version
2.0.1-beta.35

$ func init
Select a worker runtime:
1. dotnet
2. node
3. java
Choose option: 2
node
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing /private/tmp/ehfunc/.vscode/extensions.json

$ func new
Select a language: Select a template:
1. Blob trigger
2. Cosmos DB trigger
3. Event Grid trigger
4. HTTP trigger
5. Queue trigger
6. SendGrid
7. Service Bus Queue trigger
8. Service Bus Topic trigger
9. Timer `trigger`
Choose option:
```

OS: macOs 10.13.6

_Copied from original issue: Azure/azure-functions-core-tools#669_

**Comment by EricJizbaMSFT** [comment]
Same behavior for the VS Code extension as pointed out by @timmyreilly. We don't see EventHub listed in the v2 JavaScript templates from the cli-feed.

**Comment by soninaren** [comment]
This is fixed now
