### ISSUE TITLE
Update default project template for V2 to be .NET core 2.1

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-templates#758]
Part of https://github.com/Azure/Azure-Functions/issues/805

The target framework used in our current V2 project template is `netstandard2.0`. We should switch it over to `netcoreapp2.1` once the relevant fixes have been made in Microsoft.NET.Sdk.Functions to allow this.

**Comment by deepumi** [comment]
@paulbatum According to the blog, netcore 2.0 framework support already ended on October 1 2018 correct?

https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/

How can I upgrade existing 2.0 app to 2.1 for HTTP trigger azure function?
