### ISSUE TITLE
Card should read Azure Cosmos DB

### ISSUE THREAD

**Issue by agruning** [Azure/azure-functions-templates#760]
From @ggailey777: 

Per the Cloud Style Guide, the name of our Cosmos DB service must always include Azure:

Always use Azure to distinguish the service name as an Azure service.

![image](https://user-images.githubusercontent.com/8560637/46363283-6b3d3e00-c627-11e8-988e-c0bf658fe4b6.png)

It's a legal/branding thing—they were very adamant about it in our docs.

**Comment by soninaren** [comment]
Fixed in here https://github.com/Azure/azure-functions-templates/commit/7b63c877cba16853a35f3fdba852232038d4454b

**Comment by agruning** [comment]
Hey @soninaren I don't think you should remove "trigger" from the end

**Comment by soninaren** [comment]
You are right, Good catch. i was looking at the list of bindings which did not have trigger in the end. got me confused. Have added it back. https://github.com/Azure/azure-functions-templates/commit/4a1352b6d48a21ad3c2050547cc98bb242a95781

 Though none of our other bindings in the new template UI azure branding.
![image](https://user-images.githubusercontent.com/8119379/46556534-cf683800-c89b-11e8-864b-79527cd518b3.png)

We only have it in the bindings UI.
![image](https://user-images.githubusercontent.com/8119379/46556628-076f7b00-c89c-11e8-99b8-80ec6eff8da2.png)
