### ISSUE TITLE
Add missing triggers to initial splash screen in VS templates

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-templates#775]
Right now we're missing (from what I can see):

1. Event Grid
1. Durable Functions (ideally this is the template that has the activity, orchestrator, and http_start

**Comment by soninaren** [comment]
This will be addressed in Dev 16. This is a workitem on VS Folks as we don't control that list. @nimakms Can you add this to list of work items you are tracking for Dev 16?.
