### ISSUE TITLE
csharp suffix removed makes queue name invalid

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-templates#792]
https://github.com/Azure/azure-functions-templates/blob/20bde0b0ea46ebde088f257a333501e6dd89a3e3/Functions.Templates/Templates/SendGrid-CSharp/function.json#L7

queueName can't end with "-"

**Comment by soninaren** [comment]
Addressed in https://github.com/Azure/azure-functions-templates/commit/1e4c65a5a9db8e1b2f2d87a7c7d03463f4e626f3
