### ISSUE TITLE
AuthLevel is ignored for CSharp HttpTrigger

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-templates#798]
Issue originally filed here by @davemurphysf: https://github.com/Microsoft/vscode-azurefunctions/issues/768

No matter what gets passed in, "Function" is used for the authLevel. Looks like @soninaren @fabiocav changed `AuthorizationLevel.AuthLevelValue` to `AuthorizationLevel.Function` in this PR: https://github.com/Azure/azure-functions-templates/pull/759. I'm guessing we can just change it back to fix?

**Comment by soninaren** [comment]
Fixed in https://github.com/Azure/azure-functions-templates/pull/799
