### ISSUE TITLE
Blob trigger name wrong

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-templates#801]
```javascript
context.log("JavaScript blob trigger function processed blob \n Name:", context.bindingData.name, "\n Blob Size:", myBlob.length, "Bytes");
```
name property now "blobTrigger"

**Comment by JohnReeson** [comment]
Right now in portal, with `name` I get blobName, `blobTrigger` gives me conatinerName/blobName, is there some change to be made soon?

**Comment by soninaren** [comment]
i don't think there is a change in the behavior. `blobTrigger` just gives you full path however you can still access `name` via `context.bindingData.name`

**Comment by soninaren** [comment]
fixed in here https://github.com/Azure/azure-functions-templates/commit/ccde39f3e131d50e613bc096f4e7736a2ad3f522
