### ISSUE TITLE
How do we expose the IoT Hub device ID from an Azure Event Hubs trigger using Node?

### ISSUE THREAD

**Issue by jameshowe** [Azure/azure-functions-templates#811]
Here's a snapshot of what we currently have access to in `bindingData`:

```
{
  "invocationId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "partitionContext": {
    "cancellationToken": {
      "isCancellationRequested": false,
      "canBeCanceled": true,
      "waitHandle": {
        "handle": {
          "value": 2244
        },
        "safeWaitHandle": {
          "isInvalid": false,
          "isClosed": false
        }
      }
    },
    "consumerGroupName": "xxxxxxxxxx",
    "eventHubPath": "xxxxxxxxx",
    "partitionId": "1",
    "owner": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "runtimeInformation": {
      "partitionId": "1",
      "lastSequenceNumber": 0,
      "lastEnqueuedTimeUtc": "0001-01-01T00:00:00",
      "lastEnqueuedOffset": null,
      "retrievalTime": "0001-01-01T00:00:00"
    }
  },
  "partitionKeyArray": [
    null
  ],
  "offsetArray": [
    "8600703872"
  ],
  "sequenceNumberArray": [
    167219
  ],
  "enqueuedTimeUtcArray": [
    "2018-11-26T16:21:32.334Z"
  ],
  "propertiesArray": [
    {}
  ],
  "systemPropertiesArray": [
    {
      "SequenceNumber": 167219,
      "Offset": "8600703872",
      "PartitionKey": null,
      "EnqueuedTimeUtc": "2018-11-26T16:21:32.334Z"
    }
  ],
  "sys": {
    "methodName": "EventHubTrigger",
    "utcNow": "2018-11-26T16:21:32.382474Z",
    "randGuid": "0f1c2965-8029-4c6d-bf78-e9c622e0e4e0"
  }
}
```

As per the [C#](https://stackoverflow.com/questions/42003600/azure-iot-hub-eventhub-and-functions) workaround, is there a way to expose additional metadata in Node? This is stopping me from using this trigger as my app uses the IoT Hub device ID as a ref key.

**Comment by mathewc** [comment]
As explained in an old Functions v1 SO post [here](https://stackoverflow.com/questions/42003600/azure-iot-hub-eventhub-and-functions) the iothub-connection-device-id used to be in the EventData.SystemProperties dictionary.

In Functions v2, we're using the latest EventHubs SDK, and EventData.SystemProperties has changed from an extensible dictionary to a contract type - see doc [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventdata.systempropertiescollection?view=azure-dotnet).

Our EventHub binding is populating binding data from all the EventData info we have, but it appears that the iothub-connection-device-id is no longer included in the EventData.

**Comment by pragnagopa** [comment]
Closing this as issue https://github.com/Azure/azure-webjobs-sdk/issues/2068 will be tracking fix for this.
