### ISSUE TITLE
Python HttpTrigger templates need to use "function" auth level

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-templates#822]
Currently these templates are using "anonymous" (See [here](https://github.com/Azure/azure-functions-templates/blob/ef736c5c91995065d6bc96cd7c9134de6c38c237/Functions.Templates/Templates/HttpTrigger-Python/function.json#L5)). This needs to be "function" (same as all the other language templates).

**Comment by asavaritayal** [comment]
https://github.com/Azure/azure-functions-templates/commit/0e54ad71670f89a5b21d70a6b584865ecd81c47c
