### ISSUE TITLE
SendGrid template does not handle the "ApiKey" properly.

### ISSUE THREAD

**Issue by phenning** [Azure/azure-functions-templates#841]
When creating a SendGrid template, the APIKey value ends up as the property name for the SendGrid return Attribute.

Ideally, the Name of the API key should go here, with the key/value pair being stuffed into local.settings.json. However, there is no support for modifying existing files in the functions add item dialog. The Azure Functions VS tooling team has a work item to try to address this, but in the meanwhile, we may want to consider updating the SendGrid template with a comment that explains that the user should copy this value into the local.settings.json and update the attribute value.

![image](https://user-images.githubusercontent.com/2433750/53365203-8457cb80-38f5-11e9-9a4b-7fff3d68c2fa.png)

Results in:

![image](https://user-images.githubusercontent.com/2433750/53365219-8e79ca00-38f5-11e9-82de-04a5afc9da48.png)

Which then is not runnable via F5. I had entered a valid SendGrid api key which I created from an account, and I could not get it to work until I created a key/value pair in local.settings.json, and updated attribute to be the key name rather then the value.

**Comment by soninaren** [comment]
Have updated the label in this commit https://github.com/Azure/azure-functions-templates/commit/914c6ba302394e6b3138dce51a98cb8865e953e7
