### ISSUE TITLE
Update templates to use the latest extensions.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-templates#844]

**Comment by mattchenderson** [comment]
@soninaren could you provide some description here? I think I know what this is, but not certain.

**Comment by soninaren** [comment]
This is related to template release. Currently the templates in prod do not use the latest extension packages. This is so that extensions in extension bundle and the extensions used by the templates being used in prod match. This would allows use portal templates the way they are without having to do a portal release and https://github.com/Azure/azure-functions-host/issues/3712.

**Comment by soninaren** [comment]
resolved in here https://github.com/Azure/azure-functions-templates/commit/0ce083cc8186e26d06fefc79ae0a7a13f3b304f1
