### ISSUE TITLE
Update Visual Studio item template "Connection" string to make it clearer what it does

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-templates#851]
_From @Andrew-MSFT on April 14, 2018 15:58_

Currently when a user creates a new Azure Function in Visual Studio, for trigger types that require a connection string, it just says "Connection" (VS displays this information from the item template).  

This is confusing if you don't know what it does, changing the string to "Connection String Key" would be clearer that the user is providing the key name, not the connection string itself

![image](https://user-images.githubusercontent.com/12432803/38770084-171bceb8-3fc2-11e8-84aa-dd2c7b291983.png)

_Copied from original issue: Azure/Azure-Functions#764_

**Comment by ColbyTresness** [comment]
_From @mhoeger on April 16, 2018 17:50_

@jeffhollan - This seems like a good suggestion! Would you mind triaging?

**Comment by ColbyTresness** [comment]
@nimakms I think this is in the pipeline, but adding you here in case

**Comment by ColbyTresness** [comment]
_From @JohnReeson on December 31, 2018 6:3_

See `Connection string setting` right now.

![capture](https://user-images.githubusercontent.com/35160013/50555253-99085080-0d04-11e9-9365-29b285a9f807.JPG)

**Comment by ColbyTresness** [comment]
_From @Andrew-MSFT on January 2, 2019 17:20_

Do you think "setting" is as clear as "name" or "key"?

**Comment by ColbyTresness** [comment]
_From @JohnReeson on January 3, 2019 2:33_

@Andrew-MSFT Hmm, I am just an Azure Function leaner but IMO it's fine, which indicates it's a setting in local.settings.json or app settings on Azure.  When I get started with Azure Function, I would go for the document first, where I could understand the setting. If I don't know anything about Azure Function, I would wonder why a Connection string needs a name or key.

**Comment by ColbyTresness** [comment]
I agree we should make this string clearer.

**Comment by jeffhollan** [comment]
I thought we ended up making this change? Do you know what's in prod today?

**Comment by ColbyTresness** [comment]
Yeah the above, connection string setting, is what's in prod. Naren said he'd change soon, pretty simple.

**Comment by jeffhollan** [comment]
What's the proposed new name that's more clear than "Connection string setting?"

**Comment by Andrew-MSFT** [comment]
I think this is an old issue at this point as the screenshot from when I filed it is "Connection".  I think we can close this now

**Comment by ColbyTresness** [comment]
IMO it should be "Connection string setting name", which makes it clear that we're not looking for the actual string.

**Comment by soninaren** [comment]
This addressed in the commit https://github.com/Azure/azure-functions-templates/commit/914c6ba302394e6b3138dce51a98cb8865e953e7
