### ISSUE TITLE
Event Hub Trigger Template for C# reference is not working. 

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-templates#858]
Default: 

#r "Microsoft.Azure.EventHubs"
error CS0006: Metadata file 'Microsoft.Azure.EventHubs' could not be found

When consumed:

Binding parameters to complex objects (such as 'Object') uses Json.NET serialization. 
1. Bind the parameter type as 'string' instead of 'Object' to get the raw values and avoid JSON deserialization, or
2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.

Needs to be:
#r "../bin/Microsoft.Azure.EventHubs.dll"

**Comment by soninaren** [comment]
This solution would not work if the customer is using extension bundles. You shouldn't need to reference the dll directly. Will investigate and respond. Is this v1 or v2?

**Comment by FinVamp1** [comment]
Hi Naren, this is with the Extensions installed. This is v2 and we've had another customer report this recently.

**Comment by rabrahamOpti** [comment]
@soninaren You can easily recreate this issue by creating a function app function that's triggered by an event hub in Portal, and then sending a message to the eventhub to trigger the function. See the four images below:

![InPortal](https://user-images.githubusercontent.com/28309959/64724822-beb83d00-d4c2-11e9-98ed-c826bf04b404.PNG)

![AzureEventHubTrigger](https://user-images.githubusercontent.com/28309959/64724828-c37cf100-d4c2-11e9-81d9-40a4b7c21028.PNG)

![InstallExtension](https://user-images.githubusercontent.com/28309959/64724850-c8da3b80-d4c2-11e9-92ad-04bbcaa66ac5.PNG)

![InvocationFailed](https://user-images.githubusercontent.com/28309959/64724856-cd065900-d4c2-11e9-9c55-ccbca9ae1af6.PNG)

**Comment by soninaren** [comment]
@rabrahamOpti this is a known issue. There is fix required in host to load the dll as expected in the meantime updating the template as mentioned by @FinVamp1 should fix the issue for you.
https://github.com/Azure/azure-functions-templates/issues/893

**Comment by soninaren** [comment]
fixed in here https://github.com/Azure/azure-functions-templates/commit/942534d7e720f5be1a10d022a27563cfeb246f66
