### ISSUE TITLE
Adding EdgeHub Trigger template

### ISSUE THREAD

**Issue by shizn** [Azure/azure-functions-templates#859]
Developers can run Azure Functions with EdgeHub trigger on IoT Edge devices. To consolidate the functions develop experience in VS Code across Functions on Cloud and Functions on Edge. We need to host a EdgeHub Trigger template here. So that VS Code extensions can leverage the templateID to show them during project creation stage.

**Comment by jeffhollan** [comment]
What's the timeline for when you need this?

**Comment by jeffhollan** [comment]
@soninaren does it make sense to assign this to you? The templates themselves (one c# one JavaScript) are in an email thread I added you on

**Comment by shizn** [comment]
I think no later than 1st week of May, given EventGrid ship date is end of May and we need 3 weeks to finish tooling integration.

**Comment by shizn** [comment]
Any updates on this one? Thanks!

**Comment by soninaren** [comment]
This is merged and should go out in the next deployment
