### ISSUE TITLE
Update Microsoft.NET.Sdk.Functions to latest version

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-templates#887]
As of today (06/19/2019), the latest version is 1.0.29 and the templates reference 1.0.28. There have been a few enhancements added to 29 and we should be on that version.

Opening this to update to whatever version is the latest when this is picked up.

**Comment by fabiocav** [comment]
@soninaren FYI

**Comment by soninaren** [comment]
Fixed in this commit 
https://github.com/Azure/azure-functions-templates/commit/e98fae88181081f1ab17dc8486013e4a13f61c34
