### ISSUE TITLE
Exclude sampling of requests by default in host.json templates

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-templates#906]
With the fix for https://github.com/Azure/azure-functions-host/issues/4753 in, we now need to update templates to exclude Requests from sampling. We can't do it globally because it'd be considered a breaking change, so we'll tackle it in templates.

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request"
    }
  }
}
```

Needs to be done in 3 parts
- [x] Default template `init template` for core tools
- [x] Default project template for VS (c# precompiled)
- [ ] Default host.json on function app  creation from portal

**Comment by brettsam** [comment]
@jeffhollan / @paulbatum / @soninaren FYI. 

I assume we're okay with having this set for everyone, whether or not they're using App Insights?

**Comment by paulbatum** [comment]
I don't see a downside.. if they don't have app insights, then this is just a no-op right?

**Comment by brettsam** [comment]
Yup. No downside -- just wanted to be clear.

**Comment by jeffhollan** [comment]
I also wonder if in this change we just explicitely add "samplingEnabled": true so people see it and can easily toggle off as is a constant source of support tickets

**Comment by kulkarnisonia16** [comment]
I see in https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsights, we have setting for  "samplingSettings": {"isEnabled": true} So, if we set this to false, will requests not be sampled?

**Comment by brettsam** [comment]
Correct. Setting this to false means that all telemetry is sent.

**Comment by soninaren** [comment]
blocked on https://github.com/Azure/azure-functions-host/issues/5604

**Comment by fabiocav** [comment]
Closing this as the remaining item is now tracked in Azure/azure-functions-host#5604

**Comment by jeffhollan** [comment]
Ah my heart is broken. I was hoping we'd modify to

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
          "isEnabled": true
       }
    }
  }
}
```

So folks know how to easily toggle this off.  But looks like PRs are already in to not include. Can keep an eye out if we should make that additional change so this is more easily discovered by users.  @kulkarnisonia16 I would be convinced we should add my "isEnabled" explicit on (which is already default today, it's just making it more apparent) if we still see a ton of support cases related to samples.
