### ISSUE TITLE
Template changes for 3.0

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-templates#911]
VS Code and Visual Studio will need a way to show changes for ~3 apps including:

- [x]  Microsoft.Functions.Net.SDK `3.0.0`
- [ ]  Change target framework to `netcoreapp3.1`

**Comment by jeffhollan** [comment]
/ cc @soninaren

**Comment by fabiocav** [comment]
Closing as completed.

**Comment by jeffhollan** [comment]
Thanks @fabiocav - did we end up updating to 3.1? Understand if it’s coming later but would be good to have a P1 to track that. Sometime before Jan 20 (when I’m thinking defaults are set)

**Comment by soninaren** [comment]
@jeffhollan we haven't updated the templates yet. I will update the templates in the next release since the dotnet 3.1 rollout is now complete.

**Comment by soninaren** [comment]
Here is the tracking item
https://github.com/Azure/azure-functions-templates/issues/917
