### ISSUE TITLE
Update the default message for HTTP trigger template

### ISSUE THREAD

**Issue by fiveisprime** [Azure/azure-functions-templates#919]
Hey there Functions friends!

We (DevDiv) have been running user studies on the Azure Functions experience in VS Code over the last month. One consistent thing we see is that participants don't realize they have successfully created and ran the function app because they see an "error" the first time they run the app. On first launch, they see `Please pass a name on the query string or in the request body` and they immediately think something is wrong with the app.

Can this be updated to indicate the app is running? Something like

> "Your Azure Function app is running, pass a 'name' parameter to see it working."

I'm open to whatever, I'd just like to see this be a bit friendlier.

...and maybe get rid of `sample.dat` while you're in there? <3

**Comment by soninaren** [comment]
Have opened a PR to fix this. `sample.dat` is used by portal and CLI to provide a sample request. Can't remove that.

**Comment by soninaren** [comment]
Will fix the typo
