### ISSUE TITLE
Fsharp template generates settings that don't work with Cosmos bindings

### ISSUE THREAD

**Issue by estensen** [Azure/azure-functions-templates#935]
https://github.com/Azure/Azure-Functions/issues/1177
https://stackoverflow.com/questions/60305107/cosmos-db-bindings-for-f-azure-function-fails-to-bind/60508257#60508257

**Comment by liliankasem** [comment]
Hi @estensen, appreciate the stackoverflow link but could you add a little more detail to the issue? I'm not exactly sure what is being asked for here. Is it specifically about this issue https://github.com/Azure/Azure-Functions/issues/1177, which appears to have been closed out but opened in the FSharp repo https://github.com/dotnet/fsharp/issues/8914, or the entire thread? Thanks!
