### ISSUE TITLE
[WebToolsE2E]Create Azure function project with V3(.Net Core) Empty, click host.json file, it will meet warning with: "Warning Value must conform to exactly one of the associated schemas".

### ISSUE THREAD

**Issue by phenning** [Azure/azure-functions-templates#939]
**REPRO STEPS**

1. File > New > Project > Azure Function > Next > Create > Azure Function v3(.Net Core) ~ Empty > Add.
2.Click host.json.

Error with host.json validation:

**Message**
Warning Value must conform to exactly one of the associated schemas
    Property name is not allowed by the schema at 
    Property name is not allowed by the schema at 
    or
    Property name is not allowed by the schema at FunctionApp1 C:\Users\v-liuw\source\repos\FunctionApp1\FunctionApp1\host.json 1

**Comment by phenning** [comment]
the host.json contains:
```

{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
}
```

It looks like the schema is missing a definition for the following property in
http://json.schemastore.org/host, as removing this line causes schema validation to succeed.

`      "samplingExcludedTypes": "Request",`

**Comment by Heidelberger** [comment]
Same issue, but only after updating the following nuget package from v3.0.10 (default) to v4.0.2.  Downgrading does not resolve the warning.

Microsoft.Azure.WebJobs.Extensions.Storage

**Comment by MarkAtAgilliance** [comment]
Just found this - in my case, noticed the structure had changed from the above
```
"logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
```
to:
```
"logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true
        "excludedTypes": "Request"
      }
```
.....

Ref doc [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json)

If so, maybe close this as a documented schema change.  .

**Comment by liliankasem** [comment]
> Just found this - in my case, noticed the structure had changed from the above
> 
> ```
> "logging": {
>         "applicationInsights": {
>             "samplingExcludedTypes": "Request",
>             "samplingSettings": {
>                 "isEnabled": true
>             }
> ```
> 
> to:
> 
> ```
> "logging": {
>     "applicationInsights": {
>       "samplingSettings": {
>         "isEnabled": true
>         "excludedTypes": "Request"
>       }
> ```
> 
> .....
> 
> Ref doc [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json)
> 
> If so, maybe close this as a documented schema change. .

Sounds like this is a documented change, I'll close it out. Feel free to reopen if I missed something!
