### ISSUE TITLE
Existing AZure Functions not showing under their corresponding function app

### ISSUE THREAD

**Issue by mahdyahmed85** [Azure/azure-functions-templates#949]
Hi,
I have azure function app that contains one queue triggered function everything was working fine untill a new UI update has been applied to Azure portal. Now I can't see my function inside the function app anymore. Given that the function i running fine in the background when message is added to the Queue. I also still can see all the function resources available on the KUDU portal.
I tried to create new functions inside this function app with no luck. any one can help here.
Function App Runtime version: ~1
FUnction Language: Powershell (I also tried C# and it doesn't list).
Issue happens on the new and the classic UI of the function app

**Comment by mahdyahmed85** [comment]
Any updates regarding this issue?

**Comment by daniel-refahi** [comment]
having the same issue. i have two azure function services. the files are exactly identical on KUDU but the functions are not showing up on one of them.

**Comment by whaakman** [comment]
Experiencing the same same right now. Any update on this?

**Comment by balag0** [comment]
AppName would be helpful. You can use the instructions from https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately if required.

**Comment by whaakman** [comment]
> AppName would be helpful. You can use the instructions from https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately if required.

Just happened again. Might consider just running them on AKS. This is happening to often 

have to go with the option 2 unfortunately to provide the data. 
https://signupprocessor.azurewebsites.net/api/40e088e9-69b2-4c25-964c-3d2e9516ef4b
Sunday, November 22, 2020 12:00:50 AM

**Comment by liliankasem** [comment]
@mahdyahmed85 is this still an issue? Did recreating the app solve the problem? If not, as @balag0 commented, please provide more details about your function app so we can investigate
