### ISSUE TITLE
WEBSITE_CONTENTSHARE in template causes 400 error.

### ISSUE THREAD

**Issue by vllama** [Azure/azure-functions-templates#952]
Including a value for **WEBSITE_CONTENTSHARE**  in a template causes a deployment to fail with the following error:

```
{
    "Code": "BadRequest",
    "Message": "There was a conflict. The remote server returned an error: (400) Bad Request.",
    "Target": null,
    "Details": [
        {
            "Message": "There was a conflict. The remote server returned an error: (400) Bad Request."
        },
        {
            "Code": "BadRequest"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "01020",
                "MessageTemplate": "There was a conflict. {0}",
                "Parameters": [
                    "The remote server returned an error: (400) Bad Request."
                ],
                "Code": "BadRequest",
                "Message": "There was a conflict. The remote server returned an error: (400) Bad Request."
            }
        }
    ],
    "Innererror": null
}
```

Tracking Id : a49d03b6-0b59-4cfa-8699-51ec9fd89ddb
Deployment Correlation Id : 5337b946-4400-4ddb-a359-1efc4c4454fd

**Comment by vllama** [comment]
If it is omitted, it seems to create it with the function name + a random suffix

**Comment by romerve** [comment]
Seems it's an issue with passing an existing File share as the value for WEBSITE_CONTENTSHARE 

https://github.com/Azure/bicep/issues/2732

**Comment by liliankasem** [comment]
@vllama can you provide more detail about which template in this repo you're referring to so that we can investigate?

Also, did this workaround work for you? https://github.com/Azure/bicep/issues/2732#issuecomment-943841583
