### ISSUE TITLE
Add custom handler templates

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-templates#955]
See https://github.com/Azure/azure-functions-core-tools/issues/1972

**Comment by pragnagopa** [comment]
@anthonychu - Synced up offline with @soninaren  and @yojagad . 

For portal we have two options

- Allow customers to create function app with stack `Custom` and then point to documentation on how to get started. This will be similar to Java. No updates needed from templates

or 
-  Pick a runtime such as node for sample custom handler and include it in templates. Documentation for custom handlers also uses node as an example. 

   - Pros : Templates will include node custom handler. Core tools, Ux and VS Code getting started experience will be similar to other languages

- Cons: CustomHandler apps will have app setting `WEBSITE_NODE_DEFAULT_VERSION`  on windows.

**Comment by yojagad** [comment]
One other possibility if we do pick a default language like node is, would we continue to have to enrich portal experiences based on feedback from customers for selecting other defaults (like Go for instance) ? We could always say node is the only default we support but just a thought.

**Comment by anthonychu** [comment]
Yep I was thinking option 1 for portal. Should only need to support creating the app.

I meant for this issue to discuss templates so that core tools and vs code can support creating functions when app is of type custom. It should only generate a folder with a function.json. It doesn’t need to do much more than that. In fact I think we can just copy the node templates and remove the index.js and that’s basically what I had in mind for the templates.

**Comment by pragnagopa** [comment]
@soninaren - is it possible to include templates only for CLI/VSCode and exclude for portal?

**Comment by pragnagopa** [comment]
@anthonychu - For option 1 - OK to use: https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers as getting started guide?
