### ISSUE TITLE
Add Signal R template as an item template for visual studio

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-templates#956]

**Comment by AngelosP** [comment]
In the month of May-2020 we had
•	4,330 Function projects with a reference to blob storage
•	1,751 Function projects with a reference to SignalR


cluster("ddtelinsights").database("DDTelInsights").DotnetProjects_Raw
        | where AdvancedServerTimestampUtc >= datetime(20200501) and AdvancedServerTimestampUtc < datetime(20200601)
        | where ProjectType == "Azure Function App"
        | summarize SignalRCommon = dcountif(ProjectId, References has "d1194211c29a0f81"),
                    SignalR = dcountif(ProjectId, References has "f21fad0e8e7769ab"),
                    StorageBlobs = dcountif(ProjectId, References has "c7be4bac866be338")

**Comment by fabiocav** [comment]
Pushing this to `Triaged` until we have this prioritized.

**Comment by fabiocav** [comment]
@soninaren do you have a high level scope for this?

Adding to sprint 81's backlog to see if this is something we can pick up there.

**Comment by soninaren** [comment]
On high level this workitem would include adding files required for visual studio templates and testing it on VS. Here is a sample PR that does the same for durable template v2. https://github.com/Azure/azure-functions-templates/pull/806/files

**Comment by fabiocav** [comment]
Closing as done.
