### ISSUE TITLE
Release updated templates for core-tools to staging feed.

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-templates#965]
Need to do a template release in order to get #964 out.

Then core-tools can pull it in. cc: @pragnagopa @anthonychu

**Comment by pragnagopa** [comment]
Test staging feed templates with 
- Core Tools
- VS Code

**Comment by pragnagopa** [comment]
@soninaren - Can you please tag logic apps contacts here? If they have any questions they can reach out to me or @yojagad. Thanks!

**Comment by soninaren** [comment]
cc: @nidhi-pathak, @AbodeSaafan

**Comment by pragnagopa** [comment]
@nidhi-pathak, @AbodeSaafan - We updating templates  for new feature: https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers. 

Once we have templates available in staging feed will reach out to you to for  testing template in staging feed with logic apps.

Please let me or @yojagad know if you have any specific questions.

**Comment by pragnagopa** [comment]
Instructions to test VSCode with staging feed bundles: https://github.com/microsoft/vscode-azurefunctions/issues/2193

**Comment by pragnagopa** [comment]
Verified ARM API calls to templates via geo master on a private stamp.

**Comment by pragnagopa** [comment]
Closing as testing is complete.
- Static templates release issue https://github.com/Azure/azure-functions-templates/issues/968
- Bundles release issue https://github.com/Azure/azure-functions-extension-bundles/issues/27
