### ISSUE TITLE
WebDeploy with ARM templates to Azure Functions failing with ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER

### ISSUE THREAD

**Issue by regexrowboat** [Azure/azure-functions-templates#975]
I'm trying to deploy an Azure Function app (.NET Core, functions v3) with MSDeploy using an ARM template, and I keep getting this error almost every time. This only succeeds occasionally. My function app has 5 functions that are timer-based, running every second. I'm currently using deployment slots, and I have my functions set to disabled when they're in the staging slot (via the DisabledAttribute and slot-specific setting).

ARM template I'm using to deploy:
```
{
            "apiVersion": "2018-02-01",
            "name": "[concat(variables('webAppName'), '/staging')]",
            "type": "Microsoft.Web/sites/slots",
            "kind": "app",
            "location": "[resourceGroup().location]",
            "resources": [
                {
                    "apiVersion": "2015-02-01",
                    "type": "Extensions",
                    "name": "MSDeploy",
                    "dependsOn": [
                        "[concat(resourceId('Microsoft.Web/Sites/', variables('webAppName')), '/slots/staging')]"
                    ],
                    "properties": {
                        "packageUri": "[parameters('packageUrl')]"
                    }
                }
            ]
        }
```
I'm getting this error: `ARM-MSDeploy Deploy Failed: 'Microsoft.Web.Deployment.DeploymentDetailedUnauthorizedAccessException: Unable to perform the operation ("Delete File") for the specified directory ("D:\home\site\wwwroot\bin\MyAssembly.dll"). This can occur if the server administrator has not authorized this operation for the user credentials you are using. Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER. ---&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt; Microsoft.Web.Deployment.DeploymentException: The error code was 0x80070005. ---&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt; System.UnauthorizedAccessException: Access to the path 'D:\home\site\wwwroot\bin\MyAssembly.dll' is denied. `

How do I stop this error from happening?

**Comment by liliankasem** [comment]
@regexrowboat are you still having this problem? It seems to be auth related, does this [troubleshooting guide for WebDeploy](https://docs.microsoft.com/en-us/iis/publish/troubleshooting-web-deploy/troubleshooting-web-deploy-problems-with-visual-studio#errors-with-delegation-rules) help?

We can investigate but I'm not sure it is an issue with the functions ARM template
