### ISSUE TITLE
JSON on queue becomes string "System.Collections.Hashtable" in PowerShell

### ISSUE THREAD

**Issue by pacon-vib** [Azure/azure-functions-templates#983]
The boilerplate PowerShell `run.ps1` that `func init` generates includes the following parameter declaration:

```pwsh
param([string] $QueueItem, $TriggerMetadata)
```

If you put a JSON string on the queue, then the value of `$QueueItem` becomes the string "System.Collections.Hashtable".

I changed the `param` block to cast `$QueueItem` to `[object]` instead of `[string]`, and now `$QueueItem` contains the decoded JSON object.

I don't know much about Azure Functions or PowerShell so I could be wrong, but I think the default should be something like `[object]` rather than `[string]`.

Getting `$QueueItem` as string would be convenient if it was the same string that was originally placed on the queue, but it appears something in between is recognising the JSON string and decoding it rather than passing it along as is.

Please let me know if this ticket is in the wrong place.

**Comment by fabiocav** [comment]
@AnatoliB just transferred this to the templates repo. Are you planning o n making the changes, or do you need assistance with that?

**Comment by DmytroVas** [comment]
Hi. Was it actually fixed, please? My freshly-made Azure function (powershell- Azure Queue Trigger template) gives the same error:
ERROR: Cannot find path 'C:\home\site\wwwroot\System.Collections.Hashtable' because it does not exist.

doesn't matter if  I use:
param([string]$QueueItem, $TriggerMetadata)
or
param([object]$QueueItem, $TriggerMetadata)
or
param($QueueItem, $TriggerMetadata)

Thanks.

**Comment by AnatoliB** [comment]
@DmytroVas If omitting [string] does not work for you, something else is probably wrong with your code. How do you use this parameter exactly? If you code ends up relying on the ToString conversion anyway, directly or indirectly, this is the result you will keep getting.

**Comment by kwill-MSFT** [comment]
Any plans to fix this in the template?  I just spent too much time debugging this same issue.

**Comment by AnatoliB** [comment]
@Francisco-Gamino Could you please take care of this?

**Comment by Francisco-Gamino** [comment]
Will do @AnatoliB.
