### ISSUE TITLE
F# Timer Trigger template gives "Missing Host.json"

### ISSUE THREAD

**Issue by PhalanxHead** [Azure/azure-functions-templates#986]
Hi all!

Not sure if this is an issue with the sample or Azure Functions, but I had an issue following Aaron Powell's Azure Functions directions with Azure Functions Core Tools and the F# Timer Trigger Sample.
(https://www.aaron-powell.com/posts/2020-01-13-creating-azure-functions-in-fsharp/).

Basically, when I went to run it in vscode, after applying the vscode extension settings, I'd get an error like this:
```
Host.json file in missing. Please make sure host.json file is present at C:\Users\lhedt\Desktop\Projects\PriceAutomataF#\bin\Debug\netcoreapp3.1
```
And the sample wouldn't run.

What I did to fix it is change the compile instructions in the `.fsproj` file to use `<Content Include=''host.json" />` instead of `<None Update="host.json>`.

That solved that issue, but then it complained that there was no "AzureWebJobsStorage" key in the `local.settings.json` file, even though it was clearly there. After some screwing around, I found that doing the same thing as before did the trick, and then the sample would run!

So tl;dr:
To get the F# Timer Trigger sample to run out of the box, I had to change the `.fsproj` file from 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RootNamespace>PriceAutomataF_</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="TimerTrigger.fs" />
  </ItemGroup>
</Project>
```
to
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RootNamespace>PriceAutomataF_</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="TimerTrigger.fs" />
  </ItemGroup>
</Project>
```

I don't know if this is the best solution, or if you can do anything about it, or what will happen when I deploy it to azure, but it was the only way I found to get it to work. Hoping this fix helps someone else :)

Thankyou!

**Comment by liliankasem** [comment]
@PhalanxHead It looks like this is related to these issues so I'm going to mark as a duplicate and close this one out. We'll continue to track the below issues and try to fix the templates; this is a general F# template issue rather than just the timer trigger

- https://github.com/Azure/azure-functions-templates/issues/988
- https://github.com/Azure/azure-functions-templates/pull/954
- https://github.com/Azure/azure-functions-core-tools/issues/1963
