### ISSUE TITLE
CheckResourceStrings should return “everything looks fine” if no string resources are missing after comparing

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-templates#992]
CheckResourceStrings should return “everything looks fine” if no string resources are missing after comparing.

The current output
![image](https://user-images.githubusercontent.com/12720858/97489104-5b82a780-191c-11eb-84dd-89e140647266.png)

**Comment by soninaren** [comment]
Fixed in this commit
https://github.com/Azure/azure-functions-templates/commit/cb4c850468a270028961028d91b4f6fc1826fa87
