### ISSUE TITLE
Azure Functions templates not current in latest Visual Studio?

### ISSUE THREAD

**Issue by mattjohnsonpint** [Azure/azure-functions-templates#994]
I have VS 2019 16.8.2 latest, fully updated.  Creating a new Azure Function using the C# template includes this `host.json`:

```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
}
```
The `samplingExcludedTypes` property is incorrect, and was fixed already in #937 

Why am I still getting the older version of the template?

**Comment by liliankasem** [comment]
Looks like this has been addressed now, this is the host file I see when I create a new C# function app in Visual Studio 2019:

```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
}
```

Please reopen if you're still seeing this issue!
