### ISSUE TITLE
New SDKs are still referencing older Item and Project templates in the feed.

### ISSUE THREAD

**Issue by phenning** [Azure/azure-functions-templates#998]
SignalR item template appears to have the wrong resource id from the AccessRights symbol. This causes the long description to be displayed in Visual Studio instead of "Authorization level". Which results in undesired truncation of the string and other UI issues when this template is selected.

https://github.com/Azure/azure-functions-templates/blob/b967ff16e47a9ddbeeb3cf2cfe29d5cedb812004/Functions.Templates/Templates/SignalRConnectionInfoHttpTrigger-CSharp/.template.config/vs-2017.3.host.json#L22

**Comment by phenning** [comment]
@soninaren, we are mitigating one of the more severe side effects of this in 16.9, but the long description as showing in the template.json will still be displayed.   The template should be updated to point to the correct resource id.

**Comment by soninaren** [comment]
@phenning, I am a bit confused here. So i had fixed the issue where description text was placed in the label. What is the fix needed in the resource id?

![image](https://user-images.githubusercontent.com/8119379/100793601-3c6eae00-33d1-11eb-925f-1315354bd9a4.png)

**Comment by phenning** [comment]
@soninaren Sorry, the resource id is a red herring, I had seen the updated src and assumed that the long description string was being loaded from that resource. 

What is actually happening is that the ItemTemplate entry hasn't been updated in the feed, the feed is still referencing 3.1.1582, even in the 3.15.0 release, while it looks like NuGet is still getting updated packages:

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ItemTemplates/

**Comment by soninaren** [comment]
The templates have been deployed to NuGet. The feed is behind on the release. The next core tools / tooling feed release would automatically fetch the updated templates.

**Comment by soninaren** [comment]
Going to close the issue since there is no code change required and next release should take care of the work here.
